modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
license="MIT License"
[[mods]] #mandatory
modId="databuddy" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Databuddy Example Mod" #mandatory
authors="Commoble"
# The description text for the mod (multi line!) (#mandatory)
description='''
Databuddy Example Mod
'''
